server:
  # 服务器的HTTP端口
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql:///sm_db
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 启用监控统计
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/* # 访问监控页面的路径
        login-username: admin
        login-password: admin123
        reset-enable: false # 是否允许重置监控数据
      # WebStatFilter 用于采集 web-jdbc 关联监控的数据
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # 配置监控和统计拦截的filters
      filters:
        stat: enabled # 启用 SQL 执行的统计功能
        log4j: enabled # 监控数据输出到日志文件
        wall: enabled # 启用SQL 防火墙
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group_01
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: 127.0.0.1  # 地址
      port: 6379  # 端口号
      database: 0  # 数据库索引（默认为0）
      timeout: 1800000  # 连接超时时间（毫秒）
      lettuce:
        pool:
          max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1  # 最大阻塞等待时间（负数表示没有限制）
          max-idle: 5  # 连接池中最大空闲连接
          min-idle: 0  # 连接池中最小空闲连接

#MQTT客户端
publish:
  mqtt:
    host: tcp://broker.emqx.io:1883
    clientId: mqtt_mynmyn_3
    options:
      # 这里表示会话过不过期
      cleanSession: true
      # 配置一个默认的主题，加载时不会用到，只能在需要时手动提取
      defaultTopic: devops
      timeout: 1000
      KeepAliveInterval: 10
      #断线重连方式，自动重新连接与会话不过期配合使用会导致
      #断线重新连接后会接收到断线期间的消息。需要更改设置请看password联系我
      automaticReconnect: false
      #连接超时时长，收到服务器连接确认前的等待时间，等待时间内未收到连接确认则为连接失败。
#      connectionTimeout: 3000
      # 最大链接数
      maxInflight: 100
